### ISSUE TITLE
SwiftUI onSubmit not working

### ISSUE THREAD

**Issue by federicocappelli** [dagronf/DSFSearchField#2]
Hi, 
I'm trying to use this component directly in SwiftUI, the component appears correctly and `.onReceive` is called every time the text changes.
`.onSubmit` unfortunately is never called (like in textfield), how am I supposed to intercept the keyboard return in SwiftUI?

```
DSFSearchField.SwiftUI(text: $searchText, autosaveName: AppConfig.searchHistory.rawValue)
                    .onSubmit {
                       //Perform a search
                    }
                    .onReceive(Just(searchText)) { text in
                        print(">>>>> \(text)")
                    }
```

**Comment by dagronf** [comment]
The SwiftUI component on this control was written before the `.onSubmit()` was added to SwiftUI for macOS, so I'm not surprised that you're having difficulty. 

Lemme take a look...

**Comment by federicocappelli** [comment]
Thank you @dagronf!
My temporary workaround was to add `self.sendsWholeSearchString = true` to the `setup()` so `onSearchTermChange` is called only when the return key is pressed, it works but I needed to copy your code and not using the package.

```
// Setup from init
func setup() {
	self.searchMenuTemplate = self.createSearchesMenu()
	self.bind(.value, to: self, withKeyPath: #keyPath(searchTerm), options: nil)
        self.sendsWholeSearchString = true
}
```

sendsWholeSearchString:

A Boolean value indicating whether the cell calls its search action method when the user clicks the search button or presses Return, or after each keystroke.

**Comment by dagronf** [comment]
@federicocappelli Hey mate -- it appears that SwiftUI hasn't yet provided public hooks to call into the default `onSubmit` API.

As a result, I've added two new SwiftUI API's to allow you to detect

* update calls (`.onUpdateSearchText`)
* submit calls (`.onSubmitSearchText`)

```swift
var body: some View {
   DSFSearchField.SwiftUI(
      text: $search1,
      autosaveName: "Search1"
   )
   .onUpdateSearchText { newValue in
      Swift.print("Update with new value -> \(newValue)")
   }
   .onSubmitSearchText { newValue in
      Swift.print("Submit with new value -> \(newValue)")
   }
}
```

I've also dropped 10.11 and 10.12 support (as Xcode 14 can no longer compile for 10.11/10.12) and the SPM support version to 5.4, so made these changes and updated the version number for the library to 2.0.0.

Can you try grabbing the v2.0.0 version and try it out?

Let me know what you think. Always open to hear new ideas!

**Comment by federicocappelli** [comment]
Tested and it works perfectly, thank you very much :)

![Screenshot 2023-01-27 at 11 38 32](https://user-images.githubusercontent.com/1489236/215010637-241dc8df-2048-418e-a216-12621eb8c1b5.jpg)

**Comment by dagronf** [comment]
Ah that's great news.  Glad to be of help!

Thank you for your feedback and patience.
