### ISSUE TITLE
[SwiftUI] When the search string is bigger than the frame the text can't be scrolled

### ISSUE THREAD

**Issue by federicocappelli** [dagronf/DSFSearchField#3]
https://github.com/dagronf/DSFSearchField/assets/1489236/54a28066-bbb0-44e8-833c-d881a1b37a6f

When the search string is longer than the frame the text can't be scrolled left and right and the cursor disappears, I would expect the behaviour to be consistent with any other search bar. When the string is longer the text should start scrolling left (see Safari CMD+F search bar behaviour as reference)

**Comment by dagronf** [comment]
Hi @federicocappelli can you please try with the latest version (2.1.0)? I've turned on scrolling in the swiftui control by default

Cheers!

**Comment by federicocappelli** [comment]
Thank you very much @dagronf for the quick fix, I'm now using 2.2.1 and it works perfectly.

FYI If you want to see your code in action have a look here: [Torrent Hound](https://federicocappelli.com/torrenthound.html) :)
👍

**Comment by dagronf** [comment]
@federicocappelli Ah that's great news mate.  I'm surprised I didn't pick this up myself (I suppose I'm not really searching for long names so may never have triggered it).  Thanks for logging the bug!

Your app looks great!  Nice clean interface too.

btw. regarding your tip window - I have a nice [QR Code generator library](https://github.com/dagronf/QRCode) that could brighten up that QR code if you wanted hehe.

**Comment by federicocappelli** [comment]
> Your app looks great! Nice clean interface too.

It's just a little app I made for myself, all function no frills 

> btw. regarding your tip window - I have a nice [QR Code generator library](https://github.com/dagronf/QRCode) that could brighten up QR code if you wanted hehe.

Ahah! love this, it's going straight in the next update! thanks!
